version: "3.7"

services:
  modphp:
    build: docker/modphp
    container_name: modphp
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/modphp/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./docker/modphp/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-network
    depends_on:
      - db

  beanstalkd:
    build: docker/beanstalkd
    container_name: beanstalkd
    restart: always
    ports:
      - "11300:11300"
    volumes:
     - ./docker/beanstalkd/persist:/var/lib/beanstalkd
     - ./docker/beanstalkd/cache:/var/cache/beanstalkd
     - ./docker/beanstalkd/dir:/var/lib/beanstalkd
     - ./docker/beanstalkd/log:/binlog
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-network
    depends_on:
      - db


  db:
    build: docker/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=env_db
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
